name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  linter:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Lint with Clippy
      # Enable all non-default rules from
      # <https://rust-lang.github.io/rust-clippy/master/index.html> except
      # `clippy::restriction`. This group consists of inpractical requirements
      # like empty `else` after `else if`, prohibition of Unicode characters,
      # annotation of each and every `enum` and `struct` as `#[non_exhaustive]`,
      # and a ban on `mod.rs` file name. Also, its `implicit_return` rule
      # outright conflicts with `needless_return` from `clippy::style`. 
      #
      # We use `-W` because `RUSTFLAGS=-Dwarnings` turns warnings into errors
      # anyway.
      run: >
        cargo clippy
        --all-targets
        --all-features 
        --
        -W clippy::pedantic
        -W clippy::nursery
        -W clippy::cargo
  unit:
    name: Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build and run tests
      run: cargo test --verbose
