name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  linter:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Lint with Clippy
      # Enable all non-default rules from
      # <https://rust-lang.github.io/rust-clippy/master/index.html> except
      # `clippy::restriction`. From the documentation:
      #
      # > Restriction lints sometimes are in contrast with other lints or even
      # > go against idiomatic rust. These lints should only be enabled on
      # > a lint-by-lint basis and with careful consideration.
      #
      # For example, it requires empty `else` after `else if`, prohibits
      # non-latin Unicode characters, requires to annotate every `enum` and
      # `struct` as `#[non_exhaustive]`, and bans `mod.rs` file name. Also, its
      # `implicit_return` rule outright conflicts with `needless_return` from
      # `clippy::style`. 
      #
      # We use `-W` because `RUSTFLAGS=-Dwarnings` turns warnings into errors
      # anyway.
      #
      # Also, we explicitly allow some diagnostics:
      #
      # - clippy::ignored_unit_patterns: we replace a numeric name of a single
      #   enum field (like `|foo| foo.1`) with partial tuple unpacking (like
      #   `|(_, bar) bar|`) so the purpose of the field is instantly
      #   understood by a first-time reader. So replacing `_` with `()` cannot
      #   be done here
      #
      # - clippy::large_stack_frames: rctest triggers this diagnostics so
      #   disable it until we sort out what causes it
      #
      # - clippy::too_many_lines: allow large lexer matchers as
      #   the ECMAScript specification prescribes
      #  
      run: >
        cargo clippy
        --all-targets
        --all-features 
        --
        -W clippy::pedantic
        -W clippy::nursery
        -W clippy::cargo
        -A clippy::ignored_unit_patterns
        -A clippy::large_stack_frames
        -A clippy::too_many_lines
  unit:
    name: Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build and run tests
      run: cargo test
